receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

connectors:
  spanmetrics:

exporters:
  otlp_http/jaeger:
    endpoint: http://jaeger:4318
  prometheus:
    endpoint: 0.0.0.0:8889
  debug:
    verbosity: basic

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp_http/jaeger, spanmetrics, debug]
    metrics:
      receivers: [spanmetrics]
      exporters: [prometheus]
